- name: Include Variables
  include_vars: main.yml

- name: Create users
  tags: [never, create_user]
  become: yes
  import_tasks: create_user.yml

- name: Update System
  tags: [update_system]
  become: yes
  import_tasks: update_system.yml

- name: Configure datetime
  tags: [datetime]
  become: yes
  import_tasks: timedate.yml
