---
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    autoclean: yes
    update_cache: yes
    force_apt_get: yes
    install_recommends: yes

- name: Install Applications
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ applications }}"
